# Identity
HOSTNAME="arch"
USERNAME="frank"
ROOT_PASS="frank"
USER_PASS="frank"

# Kernel: "linux" or "linux-hardened"
KERNEL="linux-hardened"

# Encryption
ENCRYPT_DISK="false"
LUKS_PASS="encryption_password"

# USB Configuration (Automatically updated by install.sh)
USB_DEV=""

# Localization (Must be filled)
ZONEINFO="Africa"
REGION="Kenya"
CITY="Nairobi"