# Identity
HOSTNAME="enter_your_hostname_here"
USERNAME="enter_your_username_here"
ROOT_PASS="enter_your_root_password_here"
USER_PASS="enter_your_users_password_here"

# Kernel: "linux" or "linux-hardened"
KERNEL="linux-hardened"

# Encryption
ENCRYPT_DISK="false"
LUKS_PASS="encryption_password"

# USB Configuration (Automatically updated by install.sh)
USB_DEV=""

# Localization (Must be filled)
ZONEINFO="enter_continent_here"
REGION="enter_country_here"
CITY="enter_city_here"